<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DocTranslator.Cli\DocTranslator.Cli.csproj" />
    <ProjectReference Include="..\..\src\DocTranslator.Core\DocTranslator.Core.csproj" />
    <ProjectReference Include="..\..\src\DocTranslator.LLM\DocTranslator.LLM.csproj" />
    <ProjectReference Include="..\..\src\DocTranslator.GitHub\DocTranslator.GitHub.csproj" />
  </ItemGroup>

</Project>
